import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';

const renderItem = ({item, index})=>(
  <div key={index} className={styles.box}>
    <h1>{item.name}</h1>
    <p>{item.status}</p>
    <p>{item.species}</p>
    <p>{item.gender}</p>
    <p>{item.origin.name}</p>
    <Image src={item.image} width={50} height={50}/>
  </div>
)

const Home: NextPage = () => {
  const [data, setData] = useState([]);
  const [page, setPage] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  useEffect(()=>{
    setIsLoading(true);
    fetch(`https://rickandmortyapi.com/api/character?page=${page}`)
    .then(res=>res.json())
    .then( data => {
      console.log(data.results);
      setData(data.results);
      setIsLoading(false);
    })
  },[page])
  if (isLoading) return <p>Loading...</p>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Page</p>
      <input name='page' placeholder='page' value={page} type="number" onChange={(e)=>setPage(e.target.value)}/>

      <div>
        {data.map((item,index)=>renderItem({item,index}))}
      </div>

    </div>
  )
}

export default Home
