import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';

const renderItem = ({item, index})=>(
  <div key={index} className={styles.box}>
    <h1>{item.name}</h1>
    <Image src={item.image} width={50} height={50}/>
  </div>
)

const Home: NextPage = () => {
  const [data, setData] = useState([]);
  useEffect(()=>{
    fetch("https://rickandmortyapi.com/api/character")
    .then(res=>res.json())
    .then( data => {
      console.log(data.results);
      setData(data.results);
    })
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data.map((item,index)=>renderItem({item,index}))}
      </div>

    </div>
  )
}

export default Home
